---
kind: pipeline
name: build-8.0-images

platform:
  arch: arm
  os: linux

steps:
- name: deploy-8.0-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php8.0-phpunit9"
    cache_from:
      - walkero/phpunit-alpine:php8.0-phpunit9
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=8.0
      - PHPUNIT_VER=9.5.9
      - XDEBUG_VER=3.1.2
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push
