---
#######################################################################################
# phpunit 9 builds ####################################################################
kind: pipeline
name: phpunit9-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: deploy-8.1-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - php8.1-phpunit9-amd64
    cache_from:
      - walkero/phpunit-alpine:php8.1-phpunit9-amd64
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=8.1
      - PHPUNIT_VER=9.5.20
      - XDEBUG_VER=3.1.2
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

- name: deploy-8.0-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - php8.0-phpunit9-amd64
    cache_from:
      - walkero/phpunit-alpine:php8.0-phpunit9-amd64
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=8.0
      - PHPUNIT_VER=9.5.20
      - XDEBUG_VER=3.1.2
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

- name: deploy-7.4-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - php7.4-phpunit9-amd64
    cache_from:
      - walkero/phpunit-alpine:php7.4-phpunit9-amd64
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.4
      - PHPUNIT_VER=9.5.20
      - XDEBUG_VER=3.1.2
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

- name: deploy-7.3-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - php7.3-phpunit9-amd64
    cache_from:
      - walkero/phpunit-alpine:php7.3-phpunit9-amd64
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.3
      - PHPUNIT_VER=9.5.20
      - XDEBUG_VER=3.1.2
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push

---
kind: pipeline
name: phpunit9-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: deploy-8.1-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - php8.1-phpunit9-arm64
    cache_from:
      - walkero/phpunit-alpine:php8.1-phpunit9-arm64
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=8.1
      - PHPUNIT_VER=9.5.20
      - XDEBUG_VER=3.1.2
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

- name: deploy-8.0-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - php8.0-phpunit9-arm64
    cache_from:
      - walkero/phpunit-alpine:php8.0-phpunit9-arm64
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=8.0
      - PHPUNIT_VER=9.5.20
      - XDEBUG_VER=3.1.2
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

- name: deploy-7.4-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - php7.4-phpunit9-arm64
    cache_from:
      - walkero/phpunit-alpine:php7.4-phpunit9-arm64
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.4
      - PHPUNIT_VER=9.5.20
      - XDEBUG_VER=3.1.2
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

- name: deploy-7.3-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - php7.3-phpunit9-arm64
    cache_from:
      - walkero/phpunit-alpine:php7.3-phpunit9-arm64
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.3
      - PHPUNIT_VER=9.5.20
      - XDEBUG_VER=3.1.2
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push

---
kind: pipeline
name: manifest-phpunit-9

steps:
- name: manifest-php8.1-phpunit9
  image: plugins/manifest
  settings:
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
    target: walkero/phpunit-alpine:php8.1-phpunit9
    template: walkero/phpunit-alpine:php8.1-phpunit9-ARCH
    platforms:
      - linux/amd64
      - linux/arm64

- name: manifest-php8.0-phpunit9
  image: plugins/manifest
  settings:
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
    target: walkero/phpunit-alpine:php8.0-phpunit9
    template: walkero/phpunit-alpine:php8.0-phpunit9-ARCH
    platforms:
      - linux/amd64
      - linux/arm64

- name: manifest-php7.4-phpunit9
  image: plugins/manifest
  settings:
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
    target: walkero/phpunit-alpine:php7.4-phpunit9
    template: walkero/phpunit-alpine:php7.4-phpunit9-ARCH
    platforms:
      - linux/amd64
      - linux/arm64

- name: manifest-php7.3-phpunit9
  image: plugins/manifest
  settings:
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
    target: walkero/phpunit-alpine:php7.3-phpunit9
    template: walkero/phpunit-alpine:php7.3-phpunit9-ARCH
    platforms:
      - linux/amd64
      - linux/arm64

depends_on:
  - phpunit9-amd64
  - phpunit9-arm64

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push
