---
kind: pipeline
name: build-8.0-images

steps:
- name: deploy-8.0-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php8.0-phpunit9"
    cache_from:
      - walkero/phpunit-alpine:php8.0-phpunit9
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=8.0
      - PHPUNIT_VER=9.5.9
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-8.0-phpunit-8
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php8.0-phpunit8"
    cache_from:
      - walkero/phpunit-alpine:php8.0-phpunit8
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=8.0
      - PHPUNIT_VER=8.5.21
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-8.0-phpunit-7
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php8.0-phpunit7"
    cache_from:
      - walkero/phpunit-alpine:php8.0-phpunit7
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=8.0
      - PHPUNIT_VER=7.5.20
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push

---
kind: pipeline
name: build-7.4-images

steps:
- name: deploy-7.4-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.4-phpunit9"
    cache_from:
      - walkero/phpunit-alpine:php7.4-phpunit9
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.4
      - PHPUNIT_VER=9.5.9
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.4-phpunit-8
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.4-phpunit8"
    cache_from:
      - walkero/phpunit-alpine:php7.4-phpunit8
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.4
      - PHPUNIT_VER=8.5.21
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.4-phpunit-7
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.4-phpunit7"
    cache_from:
      - walkero/phpunit-alpine:php7.4-phpunit7
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.4
      - PHPUNIT_VER=7.5.20
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.4-phpunit-6
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.4-phpunit6"
    cache_from:
      - walkero/phpunit-alpine:php7.4-phpunit6
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.4
      - PHPUNIT_VER=6.5.14
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.4-phpunit-5
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.4-phpunit5"
    cache_from:
      - walkero/phpunit-alpine:php7.4-phpunit5
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.4
      - PHPUNIT_VER=5.7.27
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push

---
kind: pipeline
name: build-7.3-images

steps:
- name: deploy-7.3-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.3-phpunit9"
    cache_from:
      - walkero/phpunit-alpine:php7.3-phpunit9
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.3
      - PHPUNIT_VER=9.5.9
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.3-phpunit-8
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.3-phpunit8"
    cache_from:
      - walkero/phpunit-alpine:php7.3-phpunit8
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.3
      - PHPUNIT_VER=8.5.21
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.3-phpunit-7
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.3-phpunit7"
    cache_from:
      - walkero/phpunit-alpine:php7.3-phpunit7
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.3
      - PHPUNIT_VER=7.5.20
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.3-phpunit-6
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.3-phpunit6"
    cache_from:
      - walkero/phpunit-alpine:php7.3-phpunit6
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.3
      - PHPUNIT_VER=6.5.14
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.3-phpunit-5
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.3-phpunit5"
    cache_from:
      - walkero/phpunit-alpine:php7.3-phpunit5
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.3
      - PHPUNIT_VER=5.7.27
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push

---
kind: pipeline
name: build-7.2-images

steps:
- name: deploy-7.2-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.2-phpunit9"
    cache_from:
      - walkero/phpunit-alpine:php7.2-phpunit9
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.2
      - PHPUNIT_VER=9.5.9
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.2-phpunit-8
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.2-phpunit8"
    cache_from:
      - walkero/phpunit-alpine:php7.2-phpunit8
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.2
      - PHPUNIT_VER=8.5.21
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.2-phpunit-7
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.2-phpunit7"
    cache_from:
      - walkero/phpunit-alpine:php7.2-phpunit7
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.2
      - PHPUNIT_VER=7.5.20
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.2-phpunit-6
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.2-phpunit6"
    cache_from:
      - walkero/phpunit-alpine:php7.2-phpunit6
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.2
      - PHPUNIT_VER=6.5.14
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.2-phpunit-5
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.2-phpunit5"
    cache_from:
      - walkero/phpunit-alpine:php7.2-phpunit5
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.2
      - PHPUNIT_VER=5.7.27
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push

---
kind: pipeline
name: build-7.1-images

steps:
- name: deploy-7.1-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.1-phpunit9"
    cache_from:
      - walkero/phpunit-alpine:php7.1-phpunit9
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.1
      - PHPUNIT_VER=9.5.9
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.1-phpunit-8
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.1-phpunit8"
    cache_from:
      - walkero/phpunit-alpine:php7.1-phpunit8
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.1
      - PHPUNIT_VER=8.5.21
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.1-phpunit-7
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.1-phpunit7"
    cache_from:
      - walkero/phpunit-alpine:php7.1-phpunit7
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.1
      - PHPUNIT_VER=7.5.20
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.1-phpunit-6
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.1-phpunit6"
    cache_from:
      - walkero/phpunit-alpine:php7.1-phpunit6
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.1
      - PHPUNIT_VER=6.5.14
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
- name: deploy-7.1-phpunit-5
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php7.1-phpunit5"
    cache_from:
      - walkero/phpunit-alpine:php7.1-phpunit5
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=7.1
      - PHPUNIT_VER=5.7.27
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push

---
kind: pipeline
name: build-5.6-images

steps:
- name: deploy-5.6-phpunit-5
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - "php5.6-phpunit5"
    cache_from:
      - walkero/phpunit-alpine:php5.6-phpunit5
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=5.6
      - PHPUNIT_VER=5.7.27
      - XDEBUG_VER=2.9.8
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push
