---
kind: pipeline
name: build-8.1-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: deploy-8.1-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - php8.1-phpunit9-amd64
    cache_from:
      - walkero/phpunit-alpine:php8.1-phpunit9-amd64
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=8.1
      - PHPUNIT_VER=9.5.19
      - XDEBUG_VER=3.1.2
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push

---
kind: pipeline
name: build-8.1-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: deploy-8.1-phpunit-9
  image: plugins/docker
  settings:
    repo: walkero/phpunit-alpine
    tags:
      - php8.1-phpunit9-arm64
    cache_from:
      - walkero/phpunit-alpine:php8.1-phpunit9-arm64
    dockerfile: alpine/Dockerfile
    context: /drone/src/alpine/
    build_args:
      - PHP_VER=8.1
      - PHPUNIT_VER=9.5.19
      - XDEBUG_VER=3.1.2
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push

---
kind: pipeline
name: deploy-manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
    target: walkero/phpunit-alpine:php8.1-phpunit9
    template: walkero/phpunit-alpine:php8.1-phpunit9-ARCH
    platforms:
      - linux/amd64
      - linux/arm64

depends_on:
  - build-8.1-amd64
  - build-8.1-arm64

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push
