#!/usr/bin/env bash
PHP_VER=7.3
PHPUNIT_VER=8.2.1
XDEBUG_VER=2.7.2

PHPUNIT_MINOR_VER ?= $(shell echo "${PHPUNIT_VER}" | grep -oE '^[0-9]+\.[0-9]+')
TAG=php$(PHP_VER)-phpunit$(PHPUNIT_MINOR_VER)

REPO=walkero/phpunit-alpine
NAME=$(TAG)

echo "------ HOOK START - BUILD -------"
printenv

docker build -t $(REPO):$(TAG) 	\
			--build-arg PHP_VER=$(PHP_VER) 		\
			--build-arg PHPUNIT_VER=$(PHPUNIT_VER) \
			--build-arg XDEBUG_VER=$(XDEBUG_VER) .

echo "------ HOOK END - BUILD -------"