#!/usr/bin/env sh

PHP_VER=7.3
PHPUNIT_VER=8.2.1
PHPUNIT_MINOR_VER=${packversion%.*}
XDEBUG_VER=2.7.2
REPO=walkero/phpunit-alpine

TAG=php$PHP_VER-phpunit$PHPUNIT_MINOR_VER

NAME=$TAG

echo "------ HOOK START - BUILD -------"
echo $TAG
printenv

docker build -t $REPO:$TAG 	\
			--build-arg PHP_VER=$PHP_VER 		\
			--build-arg PHPUNIT_VER=$PHPUNIT_VER \
			--build-arg XDEBUG_VER=$XDEBUG_VER .

echo "------ HOOK END - BUILD -------"